=head1 NAME

stopwatch.pl - 

=head1 SYNOPSIS

  $ ./stopwatch.pl \
      --initialize 'curl -O http://memcached.googlecode.com/files/memcached-1.4.9.tar.gz' \
      --before     'tar xzf memcached-1.4.9.tar.gz' \
      --main       'cd memcached-1.4.9 && ./configure && make' \
      --after      'cd memcached-1.4.9 && make clean' \
      --finalize   'rm -rf memcached-1.4.9 && rm memcached-1.4.9.tar.gz' \
      --count 10

=head1 DESCRIPTION



=cut

